import { Open_Sans, Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.scss";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-primary",
  weight: ["300", "400", "500", "600", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-secondary",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}
